name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # or your default branch name
  workflow_dispatch:  # Allows manual trigger

env:
  AZURE_WEBAPP_NAME: shm    # Your Azure Web App name
  PYTHON_VERSION: '3.9'     # or your preferred Python version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create deployment package
      run: |
        zip -r deployment.zip . -x "*.git*"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment.zip
